#sudo: false
sudo: required
dist: trusty

language: python

# addons:
#   apt:
#     packages:
#       - oracle-java8-installer
  # hosts:
  #   - localhost

branches:
  only:
    - master

# test the server on multiple JDKs
jdk:
  - oraclejdk8

python:
  - "2.7"
  - "3.5"

before_install:
  # show java version
  - java -version
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  # get jdk_switcher
  - wget https://raw.githubusercontent.com/michaelklishin/jdk_switcher/master/jdk_switcher.sh
  - source jdk_switcher.sh
  # set to Java 8
  - jdk_switcher use oraclejdk8
  - jdk_switcher home oraclejdk8
  # update setuptools
  - pip install -U pip setuptools
  - pip install coveralls
  # show java version
  - java -version
  # start server as an experiment
  #- wget http://www.cs.arizona.edu/~hahnpowell/processors-server/current/processors-server.jar
  #- export PROCESSORS_SERVER="$(pwd)/processors-server.jar"
  #- java -Xmx3G -cp processors-server.jar NLPServer 8886

# command to install dependencies
install:
  #- pip install .
  - pip install .[test]
#  - pip install git+https://github.com/myedibleenso/py-processors.git

# command to run tests
script:
  - green -vv --run-coverage

after_success:
  # inspect log file
  - cat ~/py-processors.log
  - coveralls
